using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR.ARFoundation;

public class TapToPlace : MonoBehaviour
{
    /**
     * Detects touch on an AR plane and places a portal object.
     */
    [Tooltip("í„°ì¹˜ ëœ ìœ„ì¹˜ë¥¼ í‘œì‹œí•˜ëŠ” í…ìŠ¤íŠ¸")]
    public TextMeshProUGUI debugText;
    [Tooltip("í„°ì¹˜ëœ ì˜ì—­ì— ë‚˜íƒ€ë‚¼ ì†ê°€ë½ ëª¨ì–‘ UI")]
    public Image touchPoint;

    public ARRaycastManager arRaycastManager;
    //public List<GameObject> aotList;
    private List<ARRaycastHit> hitResults = new List<ARRaycastHit>();

    // í¬í„¸ ì¸ìŠ¤í„´ì‹± í•˜ê¸°
    private ARPlane arPlane; // get position, rotation
    public GameObject portalPrefab;
    [Tooltip("í¬í„¸ì´ ë‚˜íƒ€ë‚¬ëŠ”ì§€ ì²´í¬í•˜ëŠ” ë³€ìˆ˜")]
    private bool isPortalSpawned;

    // 8. í¬í„¸ ìƒì„± í›„ ëª¨ë“  í‰ë©´ ë¹„í™œì„±í™”í•˜ê¸°
    public ARPlaneManager arPlaneManager; // ì¼ë‹¨ ì§ì ‘ ë ˆí¼ëŸ°ì‹± í•´ë³´ì

     

    void Start()
    {
        debugText.text = "ğŸ‘‰ Move the camera slowly to detect a horizontal surface! ğŸ˜Š";
    }

    void Update()
    {

        //if (arPlane == null)
        //{
        //    arPlane = FindObjectOfType<ARPlane>();
        //    Instantiate(portalPrefab, arPlane.transform.position, arPlane.transform.rotation);
        //}

        if (!isPortalSpawned)
        {

            // í„°ì¹˜ê°€ ê°ì§€ ë˜ì—ˆì„ ë•Œë§Œ ì‹¤í–‰
            if (Input.touchCount > 0)
            {
                // í„°ì¹˜í¬ì¸íŠ¸ ì˜¤ë¸Œì íŠ¸ í™œì„±í™”
                if (!touchPoint.gameObject.activeSelf)
                {
                    touchPoint.gameObject.SetActive(true);
                }

                //Debug.Log("touch!");
                //DisplayTouchPoint();
                // ì²« ë²ˆì§¸ í„°ì¹˜ ì •ë³´ë¥¼ ê°€ì ¸ì˜´ 
                Touch touch = Input.GetTouch(0);
                Vector2 touchPosition = touch.position;

                if (touch.phase == TouchPhase.Began || touch.phase == TouchPhase.Moved)
                {

                    // Rayë¥¼ ìœë‹¤ 
                    bool hitDetected = arRaycastManager.Raycast(touchPosition, hitResults,
                        UnityEngine.XR.ARSubsystems.TrackableType.PlaneWithinPolygon);

                    // 
                    if (hitDetected)
                    {
                        Pose hitPose = hitResults[0].pose;
                        //debugText.text = $"hit! position in 3D world X:{hitPose.position.x}, Y:{hitPose.position.y}";
                        debugText.text = "Portal Spawned!";
                        // ì—¬ê¸°ì„œ ê°€ì ¸ì˜¤ëŠ” Pose.positionì€ 3D ì›”ë“œ ê³µê°„ë‚´ì˜ ì¢Œí‘œì´ë‹¤ .

                        // ìš”ê¸°ì„œ í¬í„¸ ìœ ë¬´ë¥¼ ì²´í¬í•˜ë©´ í¬í„¸ì´ ìƒì„±ë˜ì–´ë„ í‰ë©´ê°ì§€ëŠ” ê³„ì†í•´ì„œ ëœë‹¤
                        // ê·¸ëŸ¬ë¯€ë¡œ í¬í„¸ì´ ìƒì„±ëœ í›„ì—ë„ ë‹¤ë¥¸ í‰ë©´ì„ ê³„ì†í•´ì„œ ê°ì§€ê°€ ê°€ëŠ¥í•˜ì§€ë§Œ
                        // ì´ë¯¸ í¬í„¸ì´ ìƒì„±ëœ í‰ë©´ ìœ„ì— ë˜ í‰ë©´ì´ ìƒì„±ë  ìˆ˜ ìˆìŒ 
                        //if (!isPortalSpawned)
                        //{
                        arPlane = FindObjectOfType<ARPlane>();
                        Instantiate(portalPrefab, arPlane.transform.position, arPlane.transform.rotation);
                        isPortalSpawned = true;

                        //í¬í„¸ì´ ìƒì„± ë˜ì—ˆë‹¤ë©´
                        // ê¸°ì¡´ì— ê°ì§€ëœ ë‹¤ë¥¸ í‰ë©´ì„ ë¹„í™œì„±í™” 
                        arPlaneManager.SetTrackablesActive(false);
                        // AR Plane Manager ì»´í¬ë„ŒíŠ¸ë¥¼ ë¹„í™œì„±í™” 
                        arPlaneManager.enabled = false;
                        //}
                    }
                    else
                    {
                        debugText.text = "No hit.";
                    }

                }


                // í„°ì¹˜ ì •ë³´ UI í‘œì‹œ
                // í„°ì¹˜ëœ ìœ„ì¹˜ ì¢Œí‘œë¥¼ ê°€ì ¸ì˜´
                //Vector2 touchPosition = touch.position;
                // í„°ì¹˜ëœ ì¢Œí‘œë¥¼ í…ìŠ¤íŠ¸ UIì— í‘œì‹œ
                //debugText.text = $"touch position X:{touchPosition.x}, Y:{touchPosition.y}";
                // ì´ë¯¸ì§€ í‘œì‹œ
                // í„°ì¹˜ í¬ì¸íŠ¸ë¥¼ í‘œì‹œí•˜ë ¤ë©´ ìŠ¤í¬ë¦° ì¢Œí‘œ(í”½ì…€ë‹¨ìœ„)ë¥¼ ê°€ì ¸ì™€ì•¼ í•˜ê¸° ë•Œë¬¸ì— Input.GetTouch()ì˜ positionê°’ì„ ì‚¬ìš©í•œë‹¤ . 
                touchPoint.transform.position = touch.position;

            }

            if (Input.GetKeyDown(KeyCode.Space))
            {
                arPlane = FindObjectOfType<ARPlane>();
                Instantiate(portalPrefab, arPlane.transform.position, arPlane.transform.rotation);
                arPlaneManager.SetTrackablesActive(false);
                // AR Plane Manager ì»´í¬ë„ŒíŠ¸ë¥¼ ë¹„í™œì„±í™” 
                arPlaneManager.enabled = false;
                debugText.text = "Portal Spawned!";
            }

        }
    }

    //private void DisplayTouchPoint()
    //{
    //    // ì²« ë²ˆì§¸ í„°ì¹˜ ì •ë³´ë¥¼ ê°€ì ¸ì˜´ 
    //    Touch touch = Input.GetTouch(0);
    //    // í„°ì¹˜ëœ ìœ„ì¹˜ ì¢Œí‘œë¥¼ ê°€ì ¸ì˜´
    //    Vector2 touchPosition = touch.position;
    //    // í„°ì¹˜ëœ ì¢Œí‘œë¥¼ í…ìŠ¤íŠ¸ UIì— í‘œì‹œ
    //    debugText.text = $"touch position X:{touchPosition.x}, Y:{touchPosition.y}";

    //    // ì´ë¯¸ì§€ í‘œì‹œ
    //    touchPoint.transform.position = touch.position;
    //}
}
